spring:
  datasource:
    url: jdbc:postgresql://sbb2310-deploy-db.internal:5432/postgres
    username: postgres
    password: uwLngZjqsE6Ehcu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
